---
- hosts: ansible-exercise-hosts
  remote_user: root
  become: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: write out the apache configuration file
    template:
      src: /var/crash/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started

  handlers:
  - name: restart apache
    service:
      name: httpd
      state: restarted
